### ISSUE TITLE
fuzzers/074-dump_all fails, unclear why

### ISSUE THREAD

**Issue by hansfbaier** [kintex-chatter/scratchpad#6]
@unbtorsten  @jrrk2 Did this kind of error occur to you? Does it look familiar?
[fuzzfail.txt](https://github.com/kintex-chatter/scratchpad/files/8022448/fuzzfail.txt)
[error_nodes.zip](https://github.com/kintex-chatter/scratchpad/files/8022475/error_nodes.zip)
[stderr.2022-02-08T06:24:29.101305.log](https://github.com/kintex-chatter/scratchpad/files/8022443/stderr.2022-02-08T06.24.29.101305.log)
[stdout.2022-02-08T06:24:29.101305.log](https://github.com/kintex-chatter/scratchpad/files/8022445/stdout.2022-02-08T06.24.29.101305.log)

**Comment by jrrk2** [comment]
Have you checked out this section of the documentation, it might ring a bell:

074 will fail the first time, since it hasn’t been told to ignore certain wires.
After it fails, go to the build directory cd fuzzers/074-dump_all/build_<XRAY_PART> (this is the XRAY_PART from the new settings script; in our example, the build directory is fuzzers/074-dump_all/build_xc7a100tfgg676-1/).
Run python3 ../analyze_errors.py --output_ignore_list  > new-ignored
Inspect and compare new-ignored against existing ignored wire files in ../ignored_wires/.
If it looks good, copy it to an appropriately-named file: cp new-ignored ../ignored_wires/artix7/<XRAY_PART>_ignored_wires.txt (in our example, it is ../ignored_wires/artix7/xc7a100tfgg676-1_ignored_wires.txt).
Add it: git add ../ignored_wires/artix7/<XRAY_PART>_ignored_wires.txt

this is from:

https://symbiflow.readthedocs.io/projects/prjxray/en/latest/db_dev_process/newpart.html

**Comment by hansfbaier** [comment]
@jrrk2  Ah yes, I remember now. Thank you so much!
